# azure-pipelines-1.yml
trigger:
  - main

# Define the variables
variables:
  TF_VAR_CREATE_BLACK: ''
  TF_VAR_CREATE_RED: ''
  TF_VAR_ELB_TARGET: ''
  TF_VAR_WEB_AMI_BLACK: ''
  TF_VAR_WEB_AMI_RED: ''

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Print all variables for verification
  - script: |
      echo "Running with variables:"
      echo "TF_VAR_CREATE_BLACK: $(TF_VAR_CREATE_BLACK)"
      echo "TF_VAR_CREATE_RED: $(TF_VAR_CREATE_RED)"
      echo "TF_VAR_ELB_TARGET: $(TF_VAR_ELB_TARGET)"
      echo "TF_VAR_WEB_AMI_BLACK: $(TF_VAR_WEB_AMI_BLACK)"
      echo "TF_VAR_WEB_AMI_RED: $(TF_VAR_WEB_AMI_RED)"
    displayName: 'Print Build Variables'

  # Add your build steps here
  - script: |
      echo "Starting build process..."
      # Add your build commands here
    displayName: 'Build Process'