# azure-pipelines-1.yml
trigger:
  - main

variables:
  TF_VAR_CREATE_BLACK: ''
  TF_VAR_CREATE_RED: ''
  TF_VAR_ELB_TARGET: ''
  TF_VAR_WEB_AMI_BLACK: ''
  TF_VAR_WEB_AMI_RED: ''

# Use self-hosted agent pool instead of hosted
pool: 
  name: Default  # Use your self-hosted agent pool name

steps:
  - script: |
      echo "Running with variables:"
      echo "TF_VAR_CREATE_BLACK: $(TF_VAR_CREATE_BLACK)"
      echo "TF_VAR_CREATE_RED: $(TF_VAR_CREATE_RED)"
      echo "TF_VAR_ELB_TARGET: $(TF_VAR_ELB_TARGET)"
      echo "TF_VAR_WEB_AMI_BLACK: $(TF_VAR_WEB_AMI_BLACK)"
      echo "TF_VAR_WEB_AMI_RED: $(TF_VAR_WEB_AMI_RED)"
    displayName: 'Print Build Variables'

  # Add your build steps here
  - script: |
      echo "Starting build process..."
    displayName: 'Build Process'