trigger:
  - main

variables:
  - name: APPLICATION
    value: $[variables.APPLICATION]
  - name: DEPLOY_VERSION
    value: $[variables.DEPLOY_VERSION]
  - name: ENVIRONMENT
    value: $[variables.ENVIRONMENT]
  - name: TF_VAR_CREATE_BLACK
    value: $[variables.TF_VAR_CREATE_BLACK]
  - name: TF_VAR_WEB_AMI_BLACK
    value: $[variables.TF_VAR_WEB_AMI_BLACK]
  - name: TF_VAR_CREATE_RED
    value: $[variables.TF_VAR_CREATE_RED]
  - name: TF_VAR_WEB_AMI_RED
    value: $[variables.TF_VAR_WEB_AMI_RED]
  - name: TF_VAR_ELB_TARGET
    value: $[variables.TF_VAR_ELB_TARGET]

pool:
  name: Default

steps:
  - task: PowerShell@2
    displayName: 'Print Build Variables'
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Running with variables:"
        Write-Host "APPLICATION: $(APPLICATION)"
        Write-Host "DEPLOY_VERSION: $(DEPLOY_VERSION)"
        Write-Host "ENVIRONMENT: $(ENVIRONMENT)"
        Write-Host "TF_VAR_CREATE_BLACK: $(TF_VAR_CREATE_BLACK)"
        Write-Host "TF_VAR_WEB_AMI_BLACK: $(TF_VAR_WEB_AMI_BLACK)"
        Write-Host "TF_VAR_CREATE_RED: $(TF_VAR_CREATE_RED)"
        Write-Host "TF_VAR_WEB_AMI_RED: $(TF_VAR_WEB_AMI_RED)"
        Write-Host "TF_VAR_ELB_TARGET: $(TF_VAR_ELB_TARGET)"

  - task: PowerShell@2
    displayName: 'Process Variables'
    inputs:
      targetType: 'inline'
      script: |
        # Example of using the variables
        $appName = "$(APPLICATION)"           # Will be "MyApp"
        $version = "$(DEPLOY_VERSION)"        # Will be "1.0.0"
        $env = "$(ENVIRONMENT)"               # Will be "Production"
        
        Write-Host "Deploying $appName version $version to $env environment"
        
        # Check if black deployment is enabled
        if ("$(TF_VAR_CREATE_BLACK)" -eq "Yes") {
            Write-Host "Black deployment is enabled"
            # Add your black deployment logic here
        }
        
        # You can use these variables in subsequent tasks or commands
        Write-Host "##vso[task.setvariable variable=ProcessedAppName]$appName"